coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 5%
    patch:
      default:
        target: 80%

comment:
  layout: "header, diff, files"
  behavior: default

ignore:
  - "client/src/index.js"
  - "server/index.js"
  - "**/*.config.js"
  - "**/setupTests.js"