name: Test Suite

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    name: Frontend Tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: client/package-lock.json

      - name: Install dependencies
        working-directory: ./client
        run: npm install

      - name: Run frontend tests with coverage
        working-directory: ./client
        run: npm run test:coverage

      - name: List frontend coverage files
        run: ls -R ./client/coverage

  test-backend:
    runs-on: ubuntu-latest
    name: Backend Tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: server/package-lock.json

      - name: Install dependencies
        working-directory: ./server
        run: npm install

      - name: Run backend tests with coverage
        working-directory: ./server
        run: npm run test:coverage

      - name: List backend coverage files
        run: ls -R ./server/coverage

  upload-coverage:
    runs-on: ubuntu-latest
    needs: [test-frontend, test-backend]
    name: Upload Coverage to Codecov

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          files: |
            client/coverage/lcov.info
            server/coverage/lcov.info
          flags: frontend,backend
          verbose: true
          fail_ci_if_error: false
